### ISSUE TITLE
Tool cli gives "MissingOptionException" on using -help option

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega-benchmark#43]
`pravega-benchmark: latest` throws `org.apache.commons.cli.MissingOptionException` on using **-help** option
```
# ./bin/pravega-benchmark -help
org.apache.commons.cli.MissingOptionException: Missing required options: controller, stream
        at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:199)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:130)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at io.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:90)
usage: pravega-benchmark
 -consumers <arg>               number of consumers
 -controller <arg>              controller URI
 -events <arg>                  number of events/records if 'time' not
                                specified;
                                otherwise, maximum events per second by
                                producer(s) and/or number of events per
                                consumer
 -help                          Help message
 -producers <arg>               number of producers
 -readcsv <arg>                 csv file to record read latencies
 -recreate <arg>                If the stream is already existing, delete
                                it and recreate it
 -segments <arg>                Number of segments
 -size <arg>                    Size of each message (event or record)
 -stream <arg>                  Stream name
 -throughput <arg>              if > 0 , throughput in MB/s
                                if 0 , writes 'events'
                                if -1, get the maximum throughput
 -time <arg>                    number of seconds the code runs
 -transaction <arg>             Producers use transactions or not
 -transactionspercommit <arg>   Number of events before a transaction is
                                committed
 -writecsv <arg>                csv file to record write latencies
```

**Comment by kmgowda** [comment]
yes, this is an issue .. i will fix it ASAP.

**Comment by RaulGracia** [comment]
This is fixed now:
```
λ .\bin\pravega-benchmark.bat -help
usage: pravega-benchmark
 -consumers <arg>                 Number of consumers
 -controller <arg>                Controller URI
 -enableConnectionPooling <arg>   Set to false to disable connection
                                  pooling
 -events <arg>                    Number of events/records if 'time' not
                                  specified;
                                  otherwise, Maximum events per second by
                                  producer(s) and/or Number of events per
                                  consumer
 -flush <arg>                     Each producer calls flush after writing
                                  <arg> number of of events/records; Not
                                  applicable, if both producers and
                                  consumers are specified
 -help                            Help message
 -producers <arg>                 Number of producers
 -readcsv <arg>                   CSV file to record read latencies
 -recreate <arg>                  If the stream is already existing,
                                  delete and recreate the same
 -scope <arg>                     Scope name
 -segments <arg>                  Number of segments
 -size <arg>                      Size of each message (event or record)
 -stream <arg>                    Stream name
 -throughput <arg>                if > 0 , throughput in MB/s
                                  if 0 , writes 'events'
                                  if -1, get the maximum throughput
 -time <arg>                      Number of seconds the code runs
 -transactionspercommit <arg>     Number of events before a transaction is
                                  committed
 -writecsv <arg>                  CSV file to record write latencies
```
