### ISSUE TITLE
Pravega benchmark hang and can't recover 

### ISSUE THREAD

**Issue by dandaoatdell** [pravega/pravega-benchmark#47]
We are getting the following exception on our client (we believe the server is just too busy), and it just hang there. We're expecting it to recover and continue

        at io.pravega.shared.protocol.netty.WireCommands$AppendSetup.process(WireCommands.java:661)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.FlowHandler.lambda$channelRead$2(FlowHandler.java:209)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.pravega.client.netty.impl.FlowHandler.channelRead(FlowHandler.java:207)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at shadow.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at shadow.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at shadow.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at shadow.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at shadow.io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at shadow.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at shadow.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at shadow.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at shadow.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at shadow.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at shadow.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at shadow.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at shadow.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: java.io.IOException: Connection reset by peer
        ... 44 more
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.write(IOUtil.java:148)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
        at shadow.io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:420)
        at shadow.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
        at shadow.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360)
        at shadow.io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
        at shadow.io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
        at shadow.io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
        at shadow.io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
        at shadow.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
        at shadow.io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1013)
        at shadow.io.netty.channel.AbstractChannel.flush(AbstractChannel.java:248)
        at io.pravega.client.netty.impl.ClientConnectionImpl.sendAsync(ClientConnectionImpl.java:104)
        ... 36 more
[nioEventLoopGroup-4-4] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 2 for endpoint 10.247.113.155

...

   64270 records Writing,    9978.3 records/sec,   6.66 MB/sec,   183.3 ms avg latency,   675.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency

**Comment by timjbutler** [comment]
Could this be a pravega issue, since the client is reporting "Caused by: java.io.IOException: Connection reset by peer"?

**Comment by dandaoatdell** [comment]
I think so too and I'm looking into the cluster log. 
However, i'm expecting the benchmark should exit after the specified test time is expired. 
In this case i've asked the benchmark to run for 600 sec, once that's expired, it should of just quit rather than hanging.

**Comment by RaulGracia** [comment]
The benchmark resumes its activity if the server recovers after a failure. If the server does not recover or is malfunctioning, we cannot expect the tool to continue working as expected.
